name = "Prine"
license = "Apache2"
licenselink = "https://github.com/kris-nova/prine/blob/master/LICENSE"
description = ""
homepage = "https://nivenly.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Kris Nóva <kris@nivenly.com>"
  homepage = "https://nivenly.com"

[params]
    twitterURL = "https://twitter.com/krisnova"
    twitterText = "@krisnova"
    githubURL = "https://github.com/kris-nova"
    githubText = "kris-nova"
    discordURL = "https://discord.com/invite/QG27kwx4nf"
    discordText = "Join our official Discord!"
    youtubeURL = "https://www.youtube.com/channel/UCRvH2UexTzcbZRwCS6OxJ3w"
    youtubeText = "Official YouTube channel!"
    settingsURL = "https://nivenly.com"
    settingsText = "Tweak your site's settings."
    footerText = "First you go up. Then you come back down."


