name = "Prine"
license = "Apache2"
licenselink = "https://github.com/kris-nova/prine/blob/master/LICENSE"
description = ""
homepage = "https://nivenly.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Kris Nóva <kris@nivenly.com>"
  homepage = "https://nivenly.com"
